# Generated by Django 5.0.6 on 2024-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_account_create_date_user_plan_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
